exercism/sml

config.json
hamming/example.sml
hamming/test_hamming.sml

There is now an example program example.sml and test program test_hamming.sml for the hamming problem. When testing this code a warning for "nonexhaustive match" may appear, it can be ignored for this exercise. It is just the SML checker trying to say that the function not handle strings that are not the same length, but that is already an invariant for this problem.

Add hamming problem to Standard ML track

---

README.md
config.json
docs/EXERCISE_README_INSERT.md

The leading 'x' is kind of arbitrary. Especially now that we can set
topics on the repositories, we don't need a pattern to distinguish what
is a track or not.
The repository itself has already been renamed. GitHub redirects from
the old name to the new name, so we do not have to rush to fix links to
the old repository name, though we should update them for the sake of
clarity.
See exercism/meta#1

Remove leading 'x' from repository name

---

exercises/nth-prime/example.sml
exercises/nth-prime/nth-prime.sml
exercises/nth-prime/test_nth_prime.sml

Test files for nth-prime have been refactored in a consistent manner and provide output about which specific tests failed to the user without needing them to enter a REPL

nth-prime refactor

---

exercises/anagram/anagram.sml
exercises/anagram/test_anagram.sml

Test files for anagram have been refactored in a consistent manner and provide output about which specific tests failed to the user without needing them to enter a REPL

anagram refactor

---

exercises/accumulate/accumulate.sml
exercises/accumulate/example.sml
exercises/accumulate/test_accumulate.sml

Test files for accumulate have been refactored in a consistent manner and provide output about which specific tests failed to the user without needing them to enter a REPL

accumulate refactor

---

exercises/hamming/hamming.sml
exercises/hamming/test_hamming.sml

Test files for hamming have been refactored in a consistent manner and provide output about which specific tests failed to the user without needing them to enter a REPL

hamming refactor

---

exercises/flatten-array/example.sml
exercises/flatten-array/flatten-array.sml
exercises/flatten-array/test_flatten_array.sml

Test files for flatten-array have been refactored in a consistent manner and provide output about which specific tests failed to the user without needing them to enter a REPL

flatten-array refactor

---

config/exercise_readme.go.tmpl
exercises/accumulate/README.md
exercises/allergies/README.md
exercises/anagram/README.md
exercises/binary/README.md
exercises/flatten-array/README.md
exercises/hamming/README.md
exercises/nth-prime/README.md
exercises/raindrops/README.md

We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …

Generate static exercise README templates

---

config.json

The website isn't detecting the test suite:
http://exercism.io/exercises/sml/raindrops/test-suite
It turns out the asterisk in the `config.json`'s `test_pattern` was operating on the underscore, rather than on a dot.
In addition, the detection is made against paths, not just the basename, so I had to take off the anchor at the beginning of the pattern.
We could add a character group that matches path separators, but I think
it's probably fine to just leave the start a bit ambiguous.

Fix test pattern in config

---

bin/generate
lib/testlib.sml

REF: #46, #47 
```
bin/generate <exercise>
```
**Note:** It will fail with some exercises. Reasons: type mismatch, for instance in `wordy` the expected value is a boolean, but some test cases have `-1`.
It will generate:
- `exercises/{exercise}/{exercise}.sml`
- `exercises/{exercise}/test.sml`
- `exercises/{exercise}/testlib.sml`
- `exercises/{exercise}/example.sml`
```sml
structure Expect:
sig
val anyError: (unit -> 'a) -> expectation
val equalTo: ''a -> ''a -> expectation
val error: exn -> (unit -> 'a) -> expectation
datatype expectation = Fail of string * string | Pass
val falsy: bool -> expectation
val nearTo: real -> real -> expectation
val truthy: bool -> expectation
end
structure Test:
sig
val run: testnode -> 'a
datatype testnode =
Test of string * (unit -> Expect.expectation)
| …
```

Exercise generator and testlib

---

config.json
exercises/pangram/README.md
exercises/pangram/example.sml
exercises/pangram/pangram.sml
exercises/pangram/test.sml
exercises/pangram/testlib.sml

Add pangram exercise

---

README.md
bin/generate
exercises/flatten-array/HINTS.md
exercises/flatten-array/README.md
exercises/flatten-array/example.sml
exercises/flatten-array/flatten-array.sml
exercises/flatten-array/test.sml
exercises/flatten-array/testlib.sml
exercises/nth-prime/HINTS.md
exercises/nth-prime/README.md
exercises/nth-prime/example.sml
exercises/nth-prime/nth-prime.sml
exercises/nth-prime/test.sml
exercises/nth-prime/testlib.sml

Changes:
flatten-array: update test, README, example & stub
- add HINTS.md
generator: add extra options
- add --{test, stub, example}-only
- add --force option to bypass type mismatch
- update README with these changes
nth-prime: update test, readme, stub & example
- add HINTS.md
- fix example.sml

Update generator, flatten-array & nth-prime

---

exercises/nth-prime/.meta/hints.md

Fixes broken link to trial division wiki page.
(Looks like I fixed this in the README ages ago, but didn't realise that the part of the README this is fetched from was HINTS!)

nth-prime: fix broken hints link

---

exercises/accumulate/README.md
exercises/all-your-base/README.md
exercises/allergies/README.md
exercises/anagram/README.md
exercises/atbash-cipher/README.md
exercises/binary/README.md
exercises/bob/README.md
exercises/bracket-push/README.md
exercises/collatz-conjecture/README.md
exercises/diamond/README.md
exercises/difference-of-squares/README.md
exercises/flatten-array/README.md
exercises/hamming/README.md
exercises/hello-world/README.md
exercises/leap/README.md
exercises/list-ops/README.md
exercises/nth-prime/README.md
exercises/pangram/README.md
exercises/perfect-numbers/README.md
exercises/phone-number/README.md
exercises/pig-latin/README.md
exercises/prime-factors/README.md
exercises/raindrops/README.md
exercises/rna-transcription/README.md
exercises/roman-numerals/README.md
exercises/space-age/README.md
exercises/sum-of-multiples/README.md
exercises/two-fer/README.md

- Addresses issue #111
- Exercises now use their specific name instead of what was created by the generator
NOTES:
- some auto-formatting was done to the Markdown files by Atom, but none of it seemed harmful to me

Update READMEs for all exercises to remove boilerplate

---

exercises/prime-factors/example.sml
exercises/prime-factors/prime-factors.sml
exercises/prime-factors/test.sml

- Change stub from `factors` to `primeFactors`. This better enables solutions that aim to first generate factors and then filter primes.
- The type signature is removed from the stub cf. discussion in the commit 1649138e450fcd9f8cf6a639503460978826b566.
- Bump test to 1.1.0: exercism/problem-specifications#1154 (no-op)

prime-factors: Change stub name and signature, bump test suite

---

bin/fetch-configlet

Currently bin/fetch-configlet fails because of case sensitivity.
The awk script matches only uppercase headers, and for some reason, the
curl command has lately been returning the Location header in lowercase:
location: https://github.com/exercism/configlet/releases/tag/v3.9.2
This change makes detection of latest configlet version independent of the casing of the HTTP headers returned by curl. Perl was used in this change rather than awk.

bin/fetch-configlet: Make HTTP header detection case-insensitive

---

config.json

Before we move the SML track to v3, let's move it to v2.
This commit creates the following order of core exercises:
```
$ jq -r '.exercises[] | select(.core) | .slug' config.json
hello-world
leap
two-fer
space-age
pangram
collatz-conjecture
matching-brackets
allergies
```
This was not chosen arbitrarily or with great care, but should work first as a first approximation. This will potentially attract more students to the track, since the core exercise overview page is much more attractive than the independent mode overview.

Extend core track

---

exercises/practice/accumulate/.meta/config.json
exercises/practice/all-your-base/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/flatten-array/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/list-ops/.meta/config.json
exercises/practice/matching-brackets/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/prime-factors/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/two-fer/.meta/config.json

Each Concept and Practice Exercise will have to define a _blurb_, which is a short description of the exercise.
The blurb will be displayed on a track's exercises page and on exercise tooltips. For example:
Blurbs must be limited to 350 chars and will be truncated in some views.
For Practice Exercises that are based on an exercise defined in the problem-specification repo, the blurb must match the contents of the problem-specifications exercises, which is defined in its `metadata.yml` file. In this PR, we'll do an initial syncing of the blurb. The new [configlet](https://github.com/exercism/configlet) version will add support for doing this syncing automatically.
If the Practice Exercise was _not_ based on a problems-specifications exercise, we've used the blurb from its …

🤖 Add blurb to .meta/config.json files

---

README.md
docs/ABOUT.md
docs/LEARNING.md
exercises/practice/bob/.meta/description.md
exercises/practice/flatten-array/.docs/instructions.append.md
exercises/practice/nth-prime/.docs/instructions.append.md

We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17

[v3] Update Markdown files to latest spec

---

exercises/practice/accumulate/.meta/tests.toml
exercises/practice/all-your-base/.meta/tests.toml
exercises/practice/allergies/.meta/tests.toml
exercises/practice/anagram/.meta/tests.toml
exercises/practice/atbash-cipher/.meta/tests.toml
exercises/practice/binary/.meta/tests.toml
exercises/practice/bob/.meta/tests.toml
exercises/practice/collatz-conjecture/.meta/tests.toml
exercises/practice/diamond/.meta/tests.toml
exercises/practice/difference-of-squares/.meta/tests.toml
exercises/practice/flatten-array/.meta/tests.toml
exercises/practice/hamming/.meta/tests.toml
exercises/practice/hello-world/.meta/tests.toml
exercises/practice/leap/.meta/tests.toml
exercises/practice/list-ops/.meta/tests.toml
exercises/practice/matching-brackets/.meta/tests.toml
exercises/practice/nth-prime/.meta/tests.toml
exercises/practice/pangram/.meta/tests.toml
exercises/practice/perfect-numbers/.meta/tests.toml
exercises/practice/phone-number/.meta/tests.toml
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/prime-factors/.meta/tests.toml
exercises/practice/raindrops/.meta/tests.toml
exercises/practice/rna-transcription/.meta/tests.toml
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/space-age/.meta/tests.toml
exercises/practice/sum-of-multiples/.meta/tests.toml
exercises/practice/two-fer/.meta/tests.toml

We're in the process of re-opening the [Problem Specifications repo](https://github.com/exercism/problem-specifications), as discussed in [this issue](https://github.com/exercism/problem-specifications/issues/1674).
This PR adds `.meta/tests.toml` files for all exercises for which canonical data is defined in the Problem Specifications repo.
We'll now discuss _why_ we're making this change.
While most of the changes to the Problem Specifications repo are specific to that repo, there is one track-specific change:
> If a track implements an exercise for which test data exists, the exercise _must_ contain a `.meta/tests.toml` file.
The goal of the `tests.toml` file is to keep track of which tests are implemented by the exercise.
Tests in this file are identified by their UUID and each test …

Bringing your track in line with the latest changes to Problem Specifications

---

exercises/practice/accumulate/.meta/config.json
exercises/practice/all-your-base/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/flatten-array/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/list-ops/.meta/config.json
exercises/practice/matching-brackets/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/prime-factors/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/two-fer/.meta/config.json

_If you got tagged in this PR, it is because you are being credited for work you've done in the past on Exercism here, and we want to ensure you don't miss out on the recognition you deserve 🙂_
---
With v3, we've introduced the idea of exercise authors and contributors. This information is stored in the exercises' `.meta/config.json` files (see [the docs](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-metaconfigjson)).
Concept Exercises, which are all new, already contain authors and contributors. Practice Exercises though are missing this information. In this PR, we attempt to populate the authors and contributors of Practice Exercises based on their commit history.
These are the things you, the maintainers, should do:
**For clarity, authors should …

🤖 Add authors and contributors to Practice Exercises

---

Makefile
bin/generate

Fix of Errors which made `Makefile` and `bin/generate` unusable.
Some errors are just syntax errors, others are due to the fact that the companion-repo `exercism/problem-specifications` evolved without the above mentioned files being updated.

Fix Makefile and bin/generate

---

.github/workflows/ci.yml

Since all exercism repos moved from master to main, we don't need to check for master in the workflow-scripts anymore. This change was suggested by the reviewer in my previous PR: https://github.com/exercism/sml/pull/199#discussion_r869166876.

Remove master from workflow ci.yml

---

README.md
bin/generate

I updated `./bin/generate` ~~so that on `./bin/generate [options] <some-exercise>` it tries to get the canonical data from a local clone of `problem-specifications` first. Only if this fails (e.g. because it is not there) it tries to retrieve it from github.~~ This resolves issue https://github.com/exercism/sml/issues/195.
**EDIT:** I added the option `--problem-specs-source {remote,local}` to the binary and changed the behaviour as discussed below.

Add possibility to retrieve canonical-data from local checkout of problem-specifications

---

README.md
bin/generate
exercises/practice/accumulate/testlib.sml
exercises/practice/all-your-base/testlib.sml
exercises/practice/allergies/testlib.sml
exercises/practice/anagram/testlib.sml
exercises/practice/atbash-cipher/testlib.sml
exercises/practice/binary/testlib.sml
exercises/practice/bob/testlib.sml
exercises/practice/collatz-conjecture/testlib.sml
exercises/practice/diamond/testlib.sml
exercises/practice/difference-of-squares/testlib.sml
exercises/practice/flatten-array/testlib.sml
exercises/practice/hamming/testlib.sml
exercises/practice/hello-world/testlib.sml
exercises/practice/leap/testlib.sml
exercises/practice/list-ops/testlib.sml
exercises/practice/matching-brackets/testlib.sml
exercises/practice/nth-prime/testlib.sml
exercises/practice/pangram/testlib.sml
exercises/practice/perfect-numbers/testlib.sml
exercises/practice/phone-number/testlib.sml
exercises/practice/pig-latin/testlib.sml
exercises/practice/prime-factors/testlib.sml
exercises/practice/raindrops/testlib.sml
exercises/practice/rna-transcription/testlib.sml
exercises/practice/roman-numerals/testlib.sml
exercises/practice/sum-of-multiples/testlib.sml
exercises/practice/two-fer/testlib.sml
lib/testlib.sml

I made a script to redeploy `lib/testlib.sml` to all exercises.  After testing that script I realized that `Space Age` is using an improved version of the test function `nearTo` which includes a delta.  This version of `nearTo` looks like it is more coherent to me, so I deployed it to all exercises.
~I isolated my redeploy script in its own commit.  Please read the commit message.  Basically, I figured out how to use `poly` in a shebang.  If we want to use the Makefile instead then I think there are some questions about where sml code should live that is neither a library nor an executable.  Anyway, if using unixisms is contentious, then we can change it.  If reviewers would prefer that that script gets submitted as its own PR that seems reasonable to me.  I include the updated testlib …

nearTo fix

---

config.json
exercises/practice/reverse-string/.docs/instructions.md
exercises/practice/reverse-string/.meta/config.json
exercises/practice/reverse-string/.meta/example.sml
exercises/practice/reverse-string/.meta/tests.toml
exercises/practice/reverse-string/reverse-string.sml
exercises/practice/reverse-string/test.sml
exercises/practice/reverse-string/testlib.sml

Added a new practice exercise `reverse-string` from `problem-specifications`.

Added exercise `reverse-string`

---

.github/workflows/ci.yml

The github action `ci` fails with the following error during the build of poly-ml v5.8:
```
In file included from /usr/include/pthread.h:33,
from locking.h:44,
from processes.h:38,
from sighandler.cpp:103:
sighandler.cpp:557:6: error: missing binary operator before token "("
557 | #if (PTHREAD_STACK_MIN < 4096)
|      ^~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:761: sighandler.lo] Error 1
make[3]: Leaving directory '/home/runner/work/sml/sml/polyml-5.8/libpolyml'
make[2]: *** [Makefile:801: all-recursive] Error 1
make[2]: Leaving directory '/home/runner/work/sml/sml/polyml-5.8/libpolyml'
make[1]: *** [Makefile:722: all-recursive] Error 1
make[1]: Leaving directory '/home/runner/work/sml/sml/polyml-5.8'
make: *** [Makefile:487: all] Error 2
```
The reason that this fails now and not earlier …

Quickfix for failing github action `ci`

---

exercises/practice/space-age/.meta/example.sml
exercises/practice/space-age/space-age.sml

Due too https://github.com/exercism/sml/issues/214 it is a minor inconvenience that Uranus and Neptune are in the "wrong" order in the template presented to the students. I fixed this.

Swap Uranus and Neptune in exercise `space-age`

---

exercises/practice/collatz-conjecture/.meta/tests.toml

Unlike many tracks, the Standard ML implementation for the collatz-conjecture exercise does not use the error strings - it uses `NONE` instead.
The error text in `problem-specifications` recently changed. As the `test.sml` for this exercise does not contain error text, no `test.sml` changes are needed at this time.

Sync collatz-conjecture exercise

---

exercises/practice/space-age/.meta/tests.toml

We exclude the new test as the type system prevents non-planets from being passed as planets.

Sync space-age exercise test metadata

---

config.json

We declare the following exercises as foregone:
- bank-account
- parallel-letter-frequency
These exercises require concurrency, but Standard ML does not support
this.

Forego concurrency exercises

---

bin/generate
config.json
exercises/practice/knapsack/.docs/instructions.md
exercises/practice/knapsack/.docs/introduction.md
exercises/practice/knapsack/.meta/config.json
exercises/practice/knapsack/.meta/example.sml
exercises/practice/knapsack/.meta/tests.toml
exercises/practice/knapsack/knapsack.sml
exercises/practice/knapsack/test.sml
exercises/practice/knapsack/testlib.sml

This is one of the [48in24 exercises](https://forum.exercism.org/t/48in24-exercise-08-13-knapsack/12054).

Add Knapsack exercise

---

docs/LEARNING.md

Programming in Standard ML '97: An On-line Tutorial has moved at some point - the link to skip ahead in it to "Simple applicative programming" was already updated at some point, but the other links were not.

Fix broken links in Standard ML LEARNING.md

---

config.json
exercises/practice/circular-buffer/.docs/instructions.md
exercises/practice/circular-buffer/.meta/config.json
exercises/practice/circular-buffer/.meta/example.sml
exercises/practice/circular-buffer/.meta/tests.toml
exercises/practice/circular-buffer/circular-buffer.sml
exercises/practice/circular-buffer/test.sml
exercises/practice/circular-buffer/testlib.sml

I set this one up as a full SML module. Difficulty = hard.

Add circular-buffer exercise

---

config.json

Forego dnd-character: Poly/ML lacks random functions

---

exercises/practice/anagram/.meta/tests.toml
exercises/practice/bob/.meta/tests.toml
exercises/practice/bob/test.sml
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/pig-latin/test.sml
exercises/practice/protein-translation/.meta/tests.toml
exercises/practice/protein-translation/test.sml
exercises/practice/reverse-string/.meta/tests.toml
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/test.sml

I've excluded the wide char tests and grapheme tests for anagram and reverse-string.

Sync tests

---

exercises/practice/flatten-array/.docs/instructions.md
exercises/practice/flatten-array/.docs/introduction.md
exercises/practice/flatten-array/.meta/tests.toml
exercises/practice/flatten-array/test.sml

Note that on this track we use lists instead of arrays for the flatten-array exercise.
[no important files changed]

Sync flatten-array
