exercism/sml

allergies/example.sml
allergies/test_allergies.sml
config.json

Two new files have been added: test_allergies.sml that will test a correct implemention of the allergies problem, and example.sml a sample solution.

implementation of the allergies problem for the SML track

---

anagram/example.sml
anagram/test_anagram.sml
config.json

Two new files have been added: test_anagram.sml that will test a correct implemention of the anagram problem, and example.sml a sample solution.

implementation of anagram problem for SML track

---

binary/example.sml
binary/test_binary.sml
config.json

There is now an example program binary.sml and test program test_binary.sml for the binary problem.

Add binary problem for Standard ML

---

config.json
exercises/flatten-array/example.sml
exercises/flatten-array/test_flatten_array.sml

1. Add flatten-array exercise and test cases
2. Update config.json to have flatten-array entry

Add flatten-array exercise

---

config.json

re: https://github.com/exercism/problem-specifications/issues/279

deprecate binary

---

exercises/allergies/allergies.sml
exercises/allergies/example.sml
exercises/allergies/test_allergies.sml

Test files for allergies have been refactored in a consistent manner and provide output about which specific tests failed to the user without needing them to enter a REPL

allergies refactor

---

.github/stale.yml

add probot stale.yml

---

docs/EXERCISE_README_INSERT.md
docs/INSTALLATION.md
docs/RESOURCES.md
docs/TESTS.md

update EXERCISE_README_INSERT
add INSTALLATION, TESTS, RESOURCES

add more docs

---

.travis.yml
Makefile

add Makefile and update .travis.yml
Makefile rules:
- `travis` only for added/modified exercises
- `debug` just prints some variables
- `test`  runs all the tests
- `test-{exercise}` runs a single test
travis.yml:
- no more sudo
- download & compile PolyML v5.7
- run tests

add Makefile and update .travis.yml

---

docs/ABOUT.md
docs/LEARNING.md

Added ABOUT.md and LEARNING.md.

Add user-facing documentation

---

config.json
exercises/hello-world/README.md
exercises/hello-world/example.sml
exercises/hello-world/hello-world.sml
exercises/hello-world/test.sml
exercises/hello-world/testlib.sml

add hello-world exercise

---

config.json
exercises/bob/README.md
exercises/bob/bob.sml
exercises/bob/example.sml
exercises/bob/test.sml
exercises/bob/testlib.sml

add bob exercise

---

config.json
exercises/atbash-cipher/README.md
exercises/atbash-cipher/atbash-cipher.sml
exercises/atbash-cipher/example.sml
exercises/atbash-cipher/test.sml
exercises/atbash-cipher/testlib.sml

add atbash-cipher exercise

---

config.json
exercises/perfect-numbers/README.md
exercises/perfect-numbers/example.sml
exercises/perfect-numbers/perfect-numbers.sml
exercises/perfect-numbers/test.sml
exercises/perfect-numbers/testlib.sml

[WIP] add perfect-numbers exercise

---

Makefile
bin/generate
config.json
exercises/collatz-conjecture/README.md
exercises/collatz-conjecture/collatz-conjecture.sml
exercises/collatz-conjecture/example.sml
exercises/collatz-conjecture/test.sml
exercises/collatz-conjecture/testlib.sml
exercises/leap/README.md
exercises/leap/example.sml
exercises/leap/leap.sml
exercises/leap/test.sml
exercises/leap/testlib.sml
exercises/rna-transcription/README.md
exercises/rna-transcription/example.sml
exercises/rna-transcription/rna-transcription.sml
exercises/rna-transcription/test.sml
exercises/rna-transcription/testlib.sml
exercises/two-fer/README.md
exercises/two-fer/example.sml
exercises/two-fer/test.sml
exercises/two-fer/testlib.sml
exercises/two-fer/two-fer.sml

exercises: 
- leap 
- collatz-conjecture 
- two-fer  
- rna-transcription
generator: update error message when there's no canonical data
Makefile: add stub check

Add exercises and update generator and makefile

---

README.md

README: update instructions

---

exercises/accumulate/README.md
exercises/accumulate/accumulate.sml
exercises/accumulate/example.sml
exercises/accumulate/test.sml
exercises/accumulate/testlib.sml

Update tests for the accumulate exercise in response to #80

accumulate: update tests

---

exercises/hamming/README.md
exercises/hamming/example.sml
exercises/hamming/hamming.sml
exercises/hamming/test.sml
exercises/hamming/testlib.sml

This is my first time submitting to exercism, please let me know if there is anything wrong with my commits or the pull request and I will fix it.

hamming: update README, test, stub, example

---

exercises/raindrops/README.md

This should be the last of the READMEs that needs updating, right? It looks like accumulate was already updated.

raindrops: update README

---

exercises/accumulate/README.md

I merged the wording of the previous version of the readme with the new updates from problem-specifications.

accumulate: update README

---

exercises/nth-prime/README.md

Fixes link in nth-prime README.md

nth-prime: fix link in README.md

---

config/maintainers.json

Based on this conversation, #97 (comment), I am updating the config/maintainers.json file to list myself as an alumnus.

set mcmillhj alumnus status

---

exercises/accumulate/README.md
exercises/all-your-base/README.md
exercises/allergies/README.md
exercises/anagram/README.md
exercises/atbash-cipher/README.md
exercises/binary/README.md
exercises/bob/README.md
exercises/collatz-conjecture/README.md
exercises/diamond/README.md
exercises/difference-of-squares/README.md
exercises/flatten-array/README.md
exercises/hamming/README.md
exercises/hello-world/README.md
exercises/leap/README.md
exercises/list-ops/README.md
exercises/matching-brackets/README.md
exercises/nth-prime/README.md
exercises/pangram/README.md
exercises/perfect-numbers/README.md
exercises/phone-number/README.md
exercises/pig-latin/README.md
exercises/prime-factors/README.md
exercises/raindrops/README.md
exercises/rna-transcription/README.md
exercises/roman-numerals/README.md
exercises/space-age/README.md
exercises/sum-of-multiples/README.md
exercises/two-fer/README.md

Updates out of date READMEs using configlet

Update READMEs using configlet

---

.travis.yml

I am surprised there doesn't seem to be a way to define a variable/constant in YAML and reuse it everywhere.
Closes #128

Bump Poly/ML version from 5.7 to 5.8

---

exercises/practice/accumulate/.meta/config.json
exercises/practice/all-your-base/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/flatten-array/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/list-ops/.meta/config.json
exercises/practice/matching-brackets/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/prime-factors/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/two-fer/.meta/config.json

To help tracks define the files in the exercise's `.meta/config.json` file, we've added support for defining these file patterns in the track's `config.json` file. See [this PR](https://github.com/exercism/docs/pull/58).
This PR updates the file paths defined in the `files` property of each exercise's `.meta/config.json` file according to the file patterns defined in the track's `config.json` file.
We only update a file path in the `.meta/config.json` file if:
- The file path pattern is a non-empty array in the `config.json` file
- The file path pattern is either not set or an empty array in the `.meta/config.json` file
This means that exercises that had already defined files in the `.meta/config.json` won't be touched in this PR.
Note that this PR is just an easy way for tracks to …

🤖 Sync exercise files keys based on file path patterns

---

exercises/practice/hello-world/hello-world.sml

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

exercises/practice/perfect-numbers/perfect-numbers.sml

Tests require an option. E.g. class -1 = NONE. I am not sure how this went unchanged.

Changed function signature

---

config.json

I find that the difficulty of exercises are not well described here, so I attempted to elevate the difficulty of the ones I found challenging. I used matching brackets as the relative landmark to measure difficulty.

Update difficulty for exercises

---

exercises/practice/nth-prime/.docs/instructions.append.md

I believe the wording doesn't make sense with this negation.

Remove negation

---

config.json
exercises/practice/acronym/.docs/instructions.md
exercises/practice/acronym/.meta/config.json
exercises/practice/acronym/.meta/example.sml
exercises/practice/acronym/.meta/tests.toml
exercises/practice/acronym/acronym.sml
exercises/practice/acronym/test.sml
exercises/practice/acronym/testlib.sml

Added a new practice exercise `acronym` from `problem-specifications`.

Added exercise `acronym`

---

config.json
exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/affine-cipher/.meta/config.json
exercises/practice/affine-cipher/.meta/example.sml
exercises/practice/affine-cipher/.meta/tests.toml
exercises/practice/affine-cipher/affine-cipher.sml
exercises/practice/affine-cipher/test.sml
exercises/practice/affine-cipher/testlib.sml

Added a new practice exercise `affine-cipher` from `problem-specifications`.

Added exercise `affine-cipher`

---

exercises/practice/gigasecond/.meta/config.json

I forgot so set me as the author of `gigasecond` - sorry for the noise.

Set rainij as author of exercise `gigasecond`

---

exercises/practice/accumulate/.meta/config.json
exercises/practice/all-your-base/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/flatten-array/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/list-ops/.meta/config.json
exercises/practice/matching-brackets/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/prime-factors/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/reverse-string/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/two-fer/.meta/config.json

This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.

Reformat exercise config files

---

exercises/practice/affine-cipher/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/flatten-array/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/list-ops/.meta/config.json
exercises/practice/nth-prime/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/prime-factors/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/space-age/.meta/config.json
exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/two-fer/.meta/config.json

This runs configlet sync on the practice exercise
metadata to bring in recent changes.

Sync metadata with problem-specifications

---

exercises/practice/accumulate/.docs/instructions.md
exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/all-your-base/.docs/instructions.md
exercises/practice/allergies/.docs/instructions.md
exercises/practice/anagram/.docs/instructions.md
exercises/practice/atbash-cipher/.docs/instructions.md
exercises/practice/bob/.docs/instructions.md
exercises/practice/bob/.docs/introduction.md
exercises/practice/collatz-conjecture/.docs/instructions.md
exercises/practice/diamond/.docs/instructions.md
exercises/practice/difference-of-squares/.docs/instructions.md
exercises/practice/flatten-array/.docs/instructions.md
exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/hamming/.docs/instructions.md
exercises/practice/hello-world/.docs/instructions.md
exercises/practice/leap/.docs/instructions.md
exercises/practice/list-ops/.docs/instructions.md
exercises/practice/matching-brackets/.docs/instructions.md
exercises/practice/nth-prime/.docs/instructions.md
exercises/practice/pangram/.docs/instructions.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/perfect-numbers/.docs/instructions.md
exercises/practice/phone-number/.docs/instructions.md
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/prime-factors/.docs/instructions.md
exercises/practice/raindrops/.docs/instructions.md
exercises/practice/roman-numerals/.docs/instructions.md
exercises/practice/space-age/.docs/instructions.md
exercises/practice/two-fer/.docs/instructions.md

I've run a complete sync for all the exercise introductions and instructions.
For most exercises this is mainly small tweaks to formatting and nitpicking markdown syntax and the like, though in a few places there were changes to the text to help make things less confusing.

Sync docs with problem specifications

---

config.json

Pulled from [Loyola Marymount University](https://cs.lmu.edu/~ray/notes/introml/) and [smlnj](http://www.smlnj.org/sml.html)
**SML Features**
1. **Modular**: _Powerful and flexible system supporting information hiding and genericity._
2. **Functionally Focused**: _All the benefits of functional programming with some imperative features._
3. **Static Typing**:   _Safety first! Strong guarantees about the correctness of programs at compile time._
4. **Automatic type inference**: _The compiler can often calculate type from context. Programs become concise and easier to write._
5. **Parametric polymorphism**: _Abstractions across data types - think templates in C++ or generics in Ada._
6. **Algebraic datatypes**: _Easy to define and easy to use, with robust pattern matching and …

[Track]: Add Key Features and Icons

---

config.json

used [style guide](https://www.cs.cornell.edu/courses/cs312/2001SP/style.html)
modified indentation to 2

:wrench: Configure online editor

---

exercises/practice/acronym/.docs/instructions.md
exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/all-your-base/.docs/instructions.md
exercises/practice/hello-world/.meta/config.json
exercises/practice/list-ops/.docs/instructions.md
exercises/practice/perfect-numbers/.docs/instructions.md
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pop-count/.meta/config.json

We sync the following exercises:
- acronym
- affine-cipher
- all-your-base
- hello-world
- list-ops
- perfect-numbers
- pig-latin
- pop-count

Sync exercise instructions, metadata

---

docs/LEARNING.md

Fix broken link in LEARNING.md

---

config.json
exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.docs/introduction.md
exercises/practice/largest-series-product/.meta/config.json
exercises/practice/largest-series-product/.meta/example.sml
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/largest-series-product.sml
exercises/practice/largest-series-product/test.sml
exercises/practice/largest-series-product/testlib.sml

Add larget-series-product exercise

---

exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/anagram/.docs/instructions.md
exercises/practice/collatz-conjecture/.docs/instructions.md
exercises/practice/collatz-conjecture/.docs/introduction.md
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/grains/.docs/instructions.md
exercises/practice/grains/.docs/introduction.md
exercises/practice/grains/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.docs/instructions.md
exercises/practice/luhn/.docs/introduction.md
exercises/practice/pascals-triangle/.docs/introduction.md
exercises/practice/phone-number/.docs/introduction.md
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/say/.meta/config.json
exercises/practice/sieve/.docs/instructions.md

Sync docs and metadata
